language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx

install:
  - echo $TRAVIS_OS_NAME
  
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then 
        sudo add-apt-repository ppa:ok2cqr/lazarus -y;
        sudo apt-get update -qq;
        sudo apt-get install -qq -y fpc; 
    else
        brew install fpc caskroom/cask/brew-cask;
        brew cask install fpcsrc; 
    fi
  
script:
  - mkdir build
  - cd build
  - fpc ../extern/pmake/pmake/pmake.pp -Fu../extern/pmake/pmake/ -FU. -o./pmake
  - ./pmake ..
  - ./make

notifications:
  email:
    on_success: false
    on_failure: change
